Add support for all Discord languages and translation system.
Discord-InterChat/locales pull request #2
Opened 2024-01-01 22:12 UTC by LautyDev

Hello, good afternoon, we want to tell you that together with [tnfAngel](https://github.com/tnfAngel) we have developed a translation system and we have edited it to support YML since the original version (https://github.com/FNLB-Project/Perception) uses JSON. We have added **all Discord languages** but you have to take into account the following:

- It is possible that in the translations spaces are added that are unnecessary because that's how Google translator works, you will have to fix them by hand.
- We recommend you not to put the emojis (ex: :no:) in the YML, but like this: {{emoji}} to avoid problems.

The only thing we ask for is **acknowledgement**, either on the Github, on the server or on the bot. I hope you like the system and have a good start of the year.

![jjLpmXX 1](https://github.com/Discord-InterChat/locales/assets/86755961/4db0c52f-c43c-4df1-ba8f-0e1ccc300278)

2024-01-01 22:28 UTC, browniepy commented
https://github.com/Discord-InterChat/locales/assets/68281832/eab8e954-ad68-412a-b121-81bd1934968b

2024-01-01 22:31 UTC, browniepy commented
LGTM!

2024-01-02 12:40 UTC, dev-737 commented
I've looked through the code, looks good. 🙂 Now, we just need the language experts to look at the translations. Let's wait for their thoughts.

2024-01-06 14:43 UTC, dev-737 commented
Update on this, we had around 3 different language speakers look at this so far, it looks like that the translations provided by Google translate were inaccurate and hard to understand in some places. Would it be possible to utilise some other more-accurate translation API for this?

2024-01-06 15:23 UTC, tnfAngel commented
Any recommendation? By the way, automatically translated languages ​​are intended to be a "base" as they can be modified and will not re-translate what was modified, so it is a good base and can be modified.

2024-01-07 05:30 UTC, cloudcloudskies commented
No, it's a bad base. Syntax's are messed up. Translations are so bad. Which will take a long time to fix.

2024-01-07 10:15 UTC, tnfAngel commented
> No, it's a bad base. Syntax's are messed up. Translations are so bad. Which will take a long time to fix.

Then we invite you to translate it into all Discord languages by ​​yourself ☺️

2024-01-07 13:49 UTC, LautyDev commented
@lunar-net Good morning, again we ask you (it is already the fourth time) to have a little respect and if you are not happy with the translations you can run the system on your own and make the improvements that you think are right (if you do, we would like to see them). On the other hand the syntax issue is something that was already warned in the Discord, we recommend you not to pass the emojis and links through the YML file (besides that it is code repetition). I will use as an example my mother tongue (Spanish), I have read some text and personally I understand perfectly what it means but as we have said it is a base and it can be edited perfectly. Again remember respect and clean dialogue, we are only here to help. Best regards.

2024-01-07 14:13 UTC, dev-737 commented
> Any recommendation about a free and good API? By the way, automatically translated languages ​​are intended to be a "base" as they can be modified and will not re-translate what was modified, so it is a good base and can be modified.

Afaik DeepL is a good alternative, it can be used both as a base and also as-is. The only problem is obtaining an API key, which is fortunately free, but requires payment information nonetheless :/

Further, let's get input from speakers of other languages to get a feel for which languages Google translate is good at, and use them as base translations. Meanwhile, I would greatly appreciate it if you could get input from other language speakers as well and let me know on discord :)

2024-01-12 12:03 UTC, dev-737 requested changes
@LautyDev After confirming with some translators of other languages, we can proceed with adding this! ~~Please resolve the conflicts and check the reviews so we can proceed~~ (Found out it was possible for me to commit to forks 💀 I fixed all the problems except for the emojis. I'll check about that later.)

2024-01-12 12:03 UTC, dev-737 commented on src/index.ts
> +	const yamlContent = yaml.dump(content);
```suggestion
	const yamlContent = yaml.dump(content, { lineWidth: Number.MAX_SAFE_INTEGER });
```
Its better to remove these new lines created by line width limits. Makes embeds look bulky

2024-01-12 12:03 UTC, dev-737 commented on src/locales/tr.yml
> +    {{{emoji}}}}} {{{user}}} tarafından mesaj __ ** {{deleted}}/{{total}}} ** __
```suggestion
    {{{emoji}}} {{{user}}} tarafından mesaj __ ** {{deleted}}/{{total}}} ** __
```
Looks like extra curly brackets are getting added for tr, cs, el, fi, ja, ko, lt, nl, no, th and zh translations. Could you please check? 🤔

2024-01-22 03:27 UTC, dev-737 approved these changes

2024-01-22 07:26 UTC, merged